# SISO BS-RoFormer for 2-source separation
# 72.2M parameters

_target_: model.SISOBase

num_channels: 2
num_sources: 2
input_normalize: true  # normalize input mixture for training stability

backbone_model:
  _target_: model.backbone.BSRoformer
  gradient_checkpointing: true

  tanh_mask: true
  
  # BS-RoFormer parameters
  dim: 384
  audio_channels: ${..num_channels}
  depth: 6
  time_transformer_depth: 1
  freq_transformer_depth: 1
  heads: 8
  dim_head: 48  # 384 / 8
  attn_dropout: 0.1
  ff_dropout: 0.1
  flash_attn: true

  mask_estimator_depth: 2
  mask_estimator_mult: 4

  # disable hyper-connection
  num_residual_streams: 1


loss_modules:
  wave: 
    _target_: model.loss.WaveLoss
    loss_type: "L1"
    decibel: false

  snr:
    _target_: model.loss.SNRLoss
    
  spec: 
    _target_: model.loss.MRSTFTLoss
    n_ffts: [4096, 2048, 1024, 512, 256]
    hop_sizes: [147, 147, 147, 147, 147]
    decibel_mae: false


loss_lambdas:
  # setting of BSMamba2 paper
  l1_wave: 2.0
  mrstft/l1: 1.0

